### ISSUE TITLE
filename suffix is not `YYYYMMDDhhiiss`

### ISSUE THREAD

**Issue by jnachtigall** [dolezel/react-csv-downloader#159]
In my case the filename suffix is `myfile_1586349856967.csv` for
```jsx
    <CsvDownloader
      filename="myfile"
      separator=";"
      suffix={true}
      columns={columns}
      datas={products}
    >
```
but the README says the suffix should be `YYYYMMDDhhiiss`. Should it not start with `2020` for `YYYY` then. 

Besides, an ISO time code would be better, e.g.: `2020-04-08T15:04:11Z`. https://en.wikipedia.org/wiki/ISO_8601 But that's another issue.

Thanks for the component, besides this it works pretty great :)

**Comment by dolezel** [comment]
Hmm, it is timestamp now. And I think it is better than having `:` characters in filename :/
I Will update docs...
