### ISSUE TITLE
react-csv-downloader loses columns after 1.5.0 → 1.6.0/1.8.0

### ISSUE THREAD

**Issue by karland** [dolezel/react-csv-downloader#167]
Hi, thanks for this package. 

The react-csv-downloader worked nicely and as expected until v1.5.0 for me. But now after migrating to 1.6.0+ it "loses" columns. I am not sure what happened and why?

**Comment by dolezel** [comment]
I also do not know :). Show me example code, data and expected result and I will check.

**Comment by Riyana6** [comment]
Hi. This is the most wanted package for me. Thank you so much. But, I also face the same problem. Can you help me?

**Comment by dolezel** [comment]
Can you give me an example code and data, so I can check?

**Comment by Riyana6** [comment]
Yeah sure.

### app.js

`import React from 'react';
import logo from './logo.svg';
import './App.css';

import CsvDownloader from 'react-csv-downloader';

const head = [{
  id: 'first',
  displayName: 'First column',
}, {
  id: 'second',
  displayName: 'Second column',
}];

const datas = [{
  first: 'foo',
  second: 'bar',
}, {
  first: 'foobar',
  second: 'foobar',
}];

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <CsvDownloader
          filename="myfile"
          separator=";"
          columns={head}
          datas={datas}
        />
      </header>
    </div>
  );
}

export default App;
`

![Screenshot (167)](https://user-images.githubusercontent.com/57560640/98091325-49b87b80-1eab-11eb-97d5-415eabf4ddbf.png)

**Comment by dolezel** [comment]
You should probably use the comma as a separator or configure the reader to recognize semicolon as separator.
Produced output is
```
'First column';'Second column'
'foo';'bar'
'foobar';'foobar'
```
which is IMO valid to what params were used.

**Comment by Riyana6** [comment]
Got it. Thank you so much.
