### ISSUE TITLE
CSV Content function not being imported in Typescript

### ISSUE THREAD

**Issue by himanshunaidu** [dolezel/react-csv-downloader#256]
Hello,
I tried importing 'react-csv-downloader/dist/lib/csv' and using it directly.

However, the path does not seem to be present. Getting the following error: 
"Cannot find module 'react-csv-downloader/dist/lib/csv' or its corresponding type declaration"

Edit:
I found the csv function in the following path
'react-csv-downloader/dist/cjs/lib/csv'

Please consider updating the doc

**Comment by dolezel** [comment]
@himanshunaidu Sorry for the confusion and thanks for reporting. Yes, I need to update the docs...
