### ISSUE TITLE
npm engines are really restrictive and cause warnings

### ISSUE THREAD

**Issue by mikecousins** [dolezel/react-csv-downloader#266]
![image](https://user-images.githubusercontent.com/725614/124681080-015fbc00-de85-11eb-87e0-5302284748ec.png)

Any chance you can remove it or make it more flexible?

**Comment by grahammcculloch** [comment]
@dolezel sorry - what is the specific reason to require ^7? Is there an incompatibility with npm 6? It still seems super restrictive! We can't use this package because we are using npm v6.
