### ISSUE TITLE
Cannot install this package with the lastest npm version 8.1.0 with Node version 16.13.0

### ISSUE THREAD

**Issue by SharjeelNasir1** [dolezel/react-csv-downloader#294]

**Comment by SharjeelNasir1** [comment]
Can you please fix this quickly?
Thanks.

**Comment by SharjeelNasir1** [comment]
@m14t @gCaste @herbertpimentel

**Comment by Sofiane000** [comment]
Is there any chance we get a quick answer if this can happen soon even as a beta build or should I just drop this  package and find a different package?
Please any idea on time line will help immensely

**Comment by jayanthsaikiran** [comment]
Can we create a new sheet/tab in csv ?

**Comment by dolezel** [comment]
Works in node v16.13.1 (npm v8.1.2)
