### ISSUE TITLE
Does not respect the order of the header

### ISSUE THREAD

**Issue by JimmyTMz** [dolezel/react-csv-downloader#335]
Hi
const columns = [
    { displayName: 'First', id: '1' },
    { displayName: 'Second', id: '1' },
    { displayName: 'Third', id: '3' }
 ]

If the information arrives [Third, Second, First] (axios), it is displayed in this way.
Expected result:
[First, Second, Third]

The header should order the order of the columns in the csv file

**Comment by dolezel** [comment]
Currently changing order for simple arrays does not work. You would need to return rows as `{'3': 'Third', '2': 'Second', '1': 'First'}`

**Comment by dolezel** [comment]
Now works with:

```
const columns = [
  { displayName: 'FirstC', id: '2' },
  { displayName: 'SecondC', id: '1' },
  { displayName: 'ThirdC', id: '0' },
]
const dataSet = [['ThirdD', 'SecondD', 'FirstD']]
```

Outputs:
```
FirstC,SecondC,ThirdC
FirstD,SecondD,ThirdD
```
