### ISSUE TITLE
add costume style to report

### ISSUE THREAD

**Issue by SultaniGithub** [dolezel/react-csv-downloader#374]
Hi,
I use this package in my project. it is great and useful. thankyou very much for this package. but, how we add some costume style in report?

**Comment by dolezel** [comment]
I have no idea what is "costume style in report"?
If you mean some colors, font props etc. that is not part of csv. You would need to use some style sheet document (Open Office format, Excel format, ...)

**Comment by SultaniGithub** [comment]
Ok, thanks.
