### ISSUE TITLE
No control over datetime field format

### ISSUE THREAD

**Issue by bradleyy1012** [dolezel/react-csv-downloader#69]
If one of the cells is a datetime field in the format MM-DD-YYYY h:mm a, it keeps formatting it as M/D/YY H:mm.
For example:
04-20-2018 4:20 pm ---> 4/20/18 16:20

Is there any way I can have it not change the data?

**Comment by dolezel** [comment]
Library makes no conversion of data just outputs it as string (for Date object it depends on locale)
So if you want some specific format, preprocess it.
