### ISSUE TITLE
Package should not require react-hot-loader to run

### ISSUE THREAD

**Issue by andrewliebchen** [dolezel/react-csv-downloader#77]
When installing with `yarn add` on a app created with `create-react-app`, I get the following error:

```
Error: ENOENT: no such file or directory, open '.../node_modules/react-hot-loader/index.js'
```

Error goes away if I add `react-hot-loader`, but I'm not it's actually needed for the core functionality of the package.

**Comment by dolezel** [comment]
That's probably bug in yarn. This package has react-hot-loader only in devDependencies which should not be installed when adding package. They are only for development purposes...

**Comment by andrewliebchen** [comment]
I wondered if this was a problem too...however, this can't be the only package on npm that use react-hot for it's dev setup. Is this just a problem for every package installed with Yarn that uses react-hot? Or is there a config that fixes it.

Either way, minor problem. Great package thanks!
